import { useState } from 'react'

type Demo = { title: string; copy: string; align: 'left' | 'right'; tone: string }
const demos: Demo[] = [
  { title: 'finally do the thing', copy: 'from first to double-click, jump into any task, ask questions, and keep moving without breaking your flow.', align: 'right', tone: 'market' },
  { title: 'use your screen as context', copy: 'if you can see it, your buddy can see it too. ask what you need and it will walk you through the next step.', align: 'left', tone: 'keyboard' },
  { title: 'speak agents with your voice', copy: 'tell it what you want in plain words. your buddy turns the small stuff into done, while you stay in control.', align: 'right', tone: 'hand' },
]
const testimonials = ['this is the most fun i’ve had learning a new tool in ages.', 'cool idea, been screenshotting and throwing stuff into ai. this is the 10x version haha.', 'wild new demo just dropped 👀', 'my new favorite onboarding experience. so unique and engaging.', 'i will tell my kids that this was built in a cave with a box of scraps.', 'literally learning how to make things right now 👀', 'can we actually get this tomorrow?', 'dear lord baby jesus please hide this from all the ai grifters.', 'the nicest way to get unstuck.']
const faqs = [['what is nudge?', 'a desktop buddy that sees what you see when you ask, then helps you learn, make, and finish the next thing.'], ['is my data private?', 'yes. the idea is that your screen is only visible after you press the hotkey. screenshots are never stored.'], ['is nudge watching my screen all the time?', 'no. it is idle until you invite it in.'], ['what can nudge actually do?', 'it can explain a tool, guide you through a task, draw on your screen, and run small actions for you.'], ['what is the difference between talk and tasks?', 'talk is the conversation. tasks are nudge actually doing the work, counted by plan.'], ['which apps does it work with?', 'anything on your screen. no plugins or integrations needed.'], ['do i need a mac?', 'this learning copy is designed for macOS first.'], ['is it free?', 'you can start for free, then choose a paid plan when you want more tasks.'], ['what happens if i hit my task limit?', 'talk keeps working. tasks pause until your next cycle or you can upgrade.'], ['can i cancel anytime?', 'yes. plans are month to month with no lock-in.']]

function DesktopMock({ tone }: { tone: string }) { return <div className={'desktop-mock ' + tone}><div className="mock-bar"><i /><i /><i /><span>nudge — helper</span></div><div className="mock-content"><div className="mock-photo" /><div className="mock-copy"><b>{tone === 'market' ? 'fresh ideas, right this way' : tone === 'keyboard' ? 'a closer look' : 'your next move'}</b><span /><span /><span /></div>{tone === 'hand' && <div className="mock-cursor">✦</div>}<div className="mock-buddy">✦</div></div></div> }
function Buddy() { return <div className="buddy-art" aria-label="abstract blue and yellow desktop companion" role="img"><span className="buddy-eye one" /><span className="buddy-eye two" /><span className="buddy-mouth" /></div> }

export default function App() {
  const [yearly, setYearly] = useState(false)
  return <div className="site">
    <header className="topbar"><a href="#top" className="brand">nudge</a><nav><a href="#notes">notes</a><a href="#feedback">feedback</a><a href="#pricing">pricing</a></nav><div className="top-actions"><a href="#faq">faq</a><a className="pill" href="#pricing">get nudge</a></div></header>
    <main id="top">
      <section className="hero"><div className="float-icon folder">▰</div><div className="float-icon smile">^ ω ^</div><div className="float-icon card">nudge<br /><small>12:32 PM</small></div><div className="float-window float-window-one"><DesktopMock tone="keyboard" /></div><div className="float-window float-window-two"><DesktopMock tone="hand" /></div><p className="tiny-label">an ai buddy for your desktop</p><h1>nudge</h1><p className="hero-sub">a tiny companion that helps you get unstuck</p><div className="hero-buttons"><a className="dark-pill" href="#demos">download for mac</a><a className="light-pill" href="#pricing">windows waitlist</a></div><small className="hero-note">macOS 14.2 or higher · 100% free to start</small><div className="hero-window"><DesktopMock tone="market" /></div><div className="hero-buddy"><Buddy /></div><div className="hero-scribble">hello<br />my name is<br /><b>nudge</b></div></section>
      <section className="demos" id="demos">{demos.map((demo) => <article className={'demo demo-' + demo.align} key={demo.title}><div className="demo-copy"><span className="speech">nudge</span><h2>{demo.title}</h2><p>{demo.copy}</p></div><DesktopMock tone={demo.tone} /><span className="audio-dots">••••••••</span></article>)}</section>
      <section className="notes" id="notes"><div className="rainbow rainbow-left" /><div className="rainbow rainbow-right" /><div className="note-card"><span className="note-label">the dream</span><p>we all have access to the same models, yet very few of us unlock their full power!</p><p>we just believe it’s an interface problem. let’s make computers feel more like they’re on your side.</p><div className="note-sign">— ari, founder <strong>nudge</strong></div></div></section>
      <section className="feedback" id="feedback"><span className="section-label">feedback</span><h2>they use it everyday <em>they use it everyday</em> they use it everyday</h2><div className="testimonial-grid">{testimonials.map((quote, i) => <article className={'testimonial t' + (i % 5)} key={quote}><div className="tweet-top"><span className="avatar" /> <b>{['sam@maker', 'william wang', 'aaron epstein', 'lenny rachitsky', 'joshua'][i % 5]}</b><span>···</span></div><p>{quote}</p><small>2:14 PM · 14 likes</small></article>)}</div><p className="count">25,000+ happy users and counting. <a href="#pricing">join them</a></p></section>
      <section className="pricing" id="pricing"><span className="section-label">pricing</span><h2>nudge, your way</h2><p>three simple plans, cancel anytime.</p><div className="toggle"><button className={!yearly ? 'active' : ''} onClick={() => setYearly(false)}>monthly</button><button className={yearly ? 'active' : ''} onClick={() => setYearly(true)}>yearly <small>-20%</small></button></div><div className="plans">{[['free', '$0', 'see what the fuss is about.', ['25 talk messages a month', 'plenty of dictation', '25 task messages a month']], ['pro', yearly ? '$16' : '$20', 'talk as much as you want.', ['unlimited talk', 'unlimited dictation', '150 task messages a month']], ['max', yearly ? '$80' : '$100', 'all the hands you need.', ['unlimited talk', 'unlimited dictation', '1,000 task messages a month']]].map(([name, price, sub, items], i) => <article className={'plan-card ' + (i === 1 ? 'popular-plan' : '')} key={name as string}>{i === 1 && <span className="popular-tag">popular</span>}<h3>{name}</h3><p>{sub}</p><strong>{price}</strong><small>per month, billed {yearly ? 'yearly' : 'monthly'}</small><a className="plan-cta" href="mailto:hello@nudge.example">{i === 0 ? 'start free' : 'get ' + name} <span>↗</span></a><h4>includes</h4><ul>{(items as string[]).map(item => <li key={item}>● {item}</li>)}</ul></article>)}</div><div className="maker-discount"><b>&lt; maker discount &gt;</b> building something cool? show us and get 50% off your first month. <a href="mailto:hello@nudge.example">reach out ↗</a></div></section>
      <section className="faq" id="faq"><span className="section-label">faq</span><h2>frequently asked questions</h2><p className="faq-sub">what to know about nudge, privacy, and getting started.</p><div className="faq-list">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    </main>
    <footer><div className="footer-links"><div><b>product</b><a href="#demos">features</a><a href="#pricing">pricing</a><a href="#feedback">feedback</a><a href="#top">try it</a></div><div><b>resources</b><a href="#faq">trust</a><a href="#faq">privacy</a><a href="mailto:hello@nudge.example">support</a></div><div><b>connect</b><a href="#top">instagram</a><a href="#top">x (twitter)</a><a href="#top">linkedin</a><a href="#top">youtube</a></div><div><b>disclaimer</b><span>nudge only sees your screen when you press the hotkey.</span></div></div><div className="footer-blocks">{Array.from({ length: 25 }, (_, i) => <i key={i} />)}</div><small>© 2026 Nudge Co. private learning copy.</small></footer>
  </div>
}
